version: "3.9"

services:

  db:
    image: postgres:16
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: bookstore_web
    working_dir: /app/bookstore
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8034:8000"
    depends_on:
      - db
    environment:
      DB_NAME: bookstore
      DB_USER: bookuser
      DB_PASSWORD: bookpass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: